language: python
sudo: false
python:
  - "2.7"
install: 
  -  "pip install pip --upgrade"
  -  "pip install setuptools --upgrade"
  -  "pip install flake8"
  - "python setup.py develop"
script: 
  - "flake8 docker_release"
  - "python setup.py install"
